BionicUniversity\Bundle\MessageBundle\Entity\Message:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        body:
            type: text
    manyToOne:
        toUser:
            targetEntity: BionicUniversity\Bundle\UserBundle\Entity\User
            inversedBy: incomingMessages
        fromUser:
            targetEntity: BionicUniversity\Bundle\UserBundle\Entity\User
            inversedBy: outcomingMessages
