BionicUniversity\Bundle\MessageBundle\Entity\Message:
    type: entity
    repositoryClass: BionicUniversity\Bundle\MessageBundle\Doctrine\ORM\MessageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        body:
            type: text
        createdAt:
            type: datetime
    manyToOne:
        toUser:
            targetEntity: BionicUniversity\Bundle\UserBundle\Entity\User
            inversedBy: incomingMessages
        fromUser:
            targetEntity: BionicUniversity\Bundle\UserBundle\Entity\User
            inversedBy: outcomingMessages